import  "./js/header"
import  "./js/footer"
import  "./js/dino-game"
import  "./js/birthday"
import  "./js/time-calculator"
import  "./js/computerGuessed"
import  "./js/rock-scissor-paper"
import  "./js/sienlist"